### ISSUE TITLE
Пример не запускается

### ISSUE THREAD

**Issue by Spearance** [unbugx/react-demo#1]
после 
npm run dev
вот с такой ошибкой
webpack: bundle is now VALID.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND react.local
    at errnoException (dns.js:25:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! React-ES6-Webpack@1.0.0 dev: `BUILD_DEV=1 webpack-dev-server --inline --devtool eval --progress --colors --hot --host react.local --port 9090`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the React-ES6-Webpack@1.0.0 dev script 'BUILD_DEV=1 webpack-dev-server --inline --devtool eval --progress --colors --hot --host react.local --port 9090'.
npm ERR! This is most likely a problem with the React-ES6-Webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     BUILD_DEV=1 webpack-dev-server --inline --devtool eval --progress --colors --hot --host react.local --port 9090
npm ERR! You can get their info via:
npm ERR!     npm owner ls React-ES6-Webpack
npm ERR! There is likely additional logging output above.

**Comment by unbugx** [comment]
Добрый день, в описании я допустил ошибку, нужно в файл hosts прописать строчку:
127.0.0.1 react.local

**Comment by Spearance** [comment]
Все отлично, спасибо!
